"""Unicode Tamil -> Bamini legacy-encoding transliteration.

Bamini is a pre-Unicode Tamil font: its glyphs live at ASCII code points
(``F`` draws கு, ``$`` draws கூ) and it maps nothing in U+0B80-U+0BFF. Unicode
Tamil therefore renders as blank boxes unless it is transliterated into Bamini's
byte encoding first. Bamini also stores the vowel signs ெ ே ை ொ ோ ௌ *before*
their consonant, so this cannot be done character-by-character - the table below
is keyed on whole grapheme clusters and matched longest-first.

The table is derived from open-tamil's ``bamini2utf8`` map, with its corrupt
entries (e.g. ``'பு10'``) dropped, its stray-backslash escapes (``'G\\+'``)
repaired, and the 13 combinations it omits - ஙு ஙூ ஞு ஞூ பூ வூ ஷு ஷூ ஸு ஸூ ஹு ஹூ -
added from the font's own glyph chart.
"""

_UNICODE_TO_BAMINI = {
    'ஸ்ரீ': '=',
    'கா': 'fh',
    'கி': 'fp',
    'கீ': 'fP',
    'கு': 'F',
    'கூ': '$',
    'கெ': 'nf',
    'கே': 'Nf',
    'கை': 'if',
    'கொ': 'nfh',
    'கோ': 'Nfh',
    'கௌ': 'nfs',
    'க்': 'f;',
    'ஙா': 'qh',
    'ஙி': 'qp',
    'ஙீ': 'qP',
    'ஙு': 'q{',
    'ஙூ': 'q_',
    'ஙெ': 'nq',
    'ஙே': 'Nq',
    'ஙை': 'iq',
    'ஙொ': 'nqh',
    'ஙோ': 'Nqh',
    'ஙௌ': 'nqs',
    'ங்': 'q;',
    'சா': 'rh',
    'சி': 'rp',
    'சீ': 'rP',
    'சு': 'R',
    'சூ': '#',
    'செ': 'nr',
    'சே': 'Nr',
    'சை': 'ir',
    'சொ': 'nrh',
    'சோ': 'Nrh',
    'சௌ': 'nrs',
    'ச்': 'r;',
    'ஜா': '[h',
    'ஜி': '[p',
    'ஜீ': '[P',
    'ஜு': '[{',
    'ஜூ': '[_',
    'ஜெ': 'n[',
    'ஜே': 'N[',
    'ஜை': 'i[',
    'ஜொ': 'n[h',
    'ஜோ': 'N[h',
    'ஜௌ': 'n[s',
    'ஜ்': '[;',
    'ஞா': 'Qh',
    'ஞி': 'Qp',
    'ஞீ': 'QP',
    'ஞு': 'Q{',
    'ஞூ': 'Q_',
    'ஞெ': 'nQ',
    'ஞே': 'NQ',
    'ஞை': 'iQ',
    'ஞொ': 'nQh',
    'ஞோ': 'NQh',
    'ஞௌ': 'nQs',
    'ஞ்': 'Q;',
    'டா': 'lh',
    'டி': 'lp',
    'டீ': 'lP',
    'டு': 'L',
    'டூ': '\\^',
    'டெ': 'nl',
    'டே': 'Nl',
    'டை': 'il',
    'டொ': 'nlh',
    'டோ': 'Nlh',
    'டௌ': 'nls',
    'ட்': 'l;',
    'ணா': 'zh',
    'ணி': 'zp',
    'ணீ': 'zP',
    'ணு': 'Z',
    'ணூ': 'Zh',
    'ணெ': 'nz',
    'ணே': 'Nz',
    'ணை': 'iz',
    'ணொ': 'nzh',
    'ணோ': 'Nzh',
    'ணௌ': 'nzs',
    'ண்': 'z;',
    'தா': 'jh',
    'தி': 'jp',
    'தீ': 'jP',
    'து': 'J',
    'தூ': 'Jh',
    'தெ': 'nj',
    'தே': 'Nj',
    'தை': 'ij',
    'தொ': 'njh',
    'தோ': 'Njh',
    'தௌ': 'njs',
    'த்': 'j;',
    'நா': 'eh',
    'நி': 'ep',
    'நீ': 'eP',
    'நு': 'E',
    'நூ': 'E}',
    'நெ': 'ne',
    'நே': 'Ne',
    'நை': 'ie',
    'நொ': 'neh',
    'நோ': 'Neh',
    'நௌ': 'nes',
    'ந்': 'e;',
    'னா': 'dh',
    'னி': 'dp',
    'னீ': 'dP',
    'னு': 'D',
    'னூ': 'D}',
    'னெ': 'nd',
    'னே': 'Nd',
    'னை': 'id',
    'னொ': 'ndh',
    'னோ': 'Ndh',
    'னௌ': 'nds',
    'ன்': 'd;',
    'பா': 'gh',
    'பி': 'gp',
    'பீ': 'gP',
    'பு': 'G',
    'பூ': 'G+',
    'பெ': 'ng',
    'பே': 'Ng',
    'பை': 'ig',
    'பொ': 'ngh',
    'போ': 'Ngh',
    'பௌ': 'ngs',
    'ப்': 'g;',
    'மா': 'kh',
    'மி': 'kp',
    'மீ': 'kP',
    'மு': 'K',
    'மூ': '%',
    'மெ': 'nk',
    'மே': 'Nk',
    'மை': 'ik',
    'மொ': 'nkh',
    'மோ': 'Nkh',
    'மௌ': 'nks',
    'ம்': 'k;',
    'யா': 'ah',
    'யி': 'ap',
    'யீ': 'aP',
    'யு': 'A',
    'யூ': 'A+',
    'யெ': 'na',
    'யே': 'Na',
    'யை': 'ia',
    'யொ': 'nah',
    'யோ': 'Nah',
    'யௌ': 'nas',
    'ய்': 'a;',
    'ரா': 'uh',
    'ரி': 'hp',
    'ரீ': 'hP',
    'ரு': 'U',
    'ரூ': '&',
    'ரெ': 'nu',
    'ரே': 'Nu',
    'ரை': 'iu',
    'ரொ': 'nuh',
    'ரோ': 'Nuh',
    'ரௌ': 'nus',
    'ர்': 'u;',
    'றா': 'wh',
    'றி': 'wp',
    'றீ': 'wP',
    'று': 'W',
    'றூ': 'Wh',
    'றெ': 'nw',
    'றே': 'Nw',
    'றை': 'iw',
    'றொ': 'nwh',
    'றோ': 'Nwh',
    'றௌ': 'nws',
    'ற்': 'w;',
    'லா': 'yh',
    'லி': 'yp',
    'லீ': 'yP',
    'லு': 'Y',
    'லூ': 'Yh',
    'லெ': 'ny',
    'லே': 'Ny',
    'லை': 'iy',
    'லொ': 'nyh',
    'லோ': 'Nyh',
    'லௌ': 'nys',
    'ல்': 'y;',
    'ளா': 'sh',
    'ளி': 'sp',
    'ளீ': 'sP',
    'ளு': 'S',
    'ளூ': 'Sh',
    'ளெ': 'ns',
    'ளே': 'Ns',
    'ளை': 'is',
    'ளொ': 'nsh',
    'ளோ': 'Nsh',
    'ளௌ': 'nss',
    'ள்': 's;',
    'ழா': 'oh',
    'ழி': 'op',
    'ழீ': 'oP',
    'ழு': 'O',
    'ழூ': '\\*',
    'ழெ': 'no',
    'ழே': 'No',
    'ழை': 'io',
    'ழொ': 'noh',
    'ழோ': 'Noh',
    'ழௌ': 'noo',
    'ழ்': 'o;',
    'வா': 'th',
    'வி': 'tp',
    'வீ': 'tP',
    'வு': 'T',
    'வூ': 'T+',
    'வெ': 'nt',
    'வே': 'Nt',
    'வை': 'it',
    'வொ': 'nth',
    'வோ': 'Nth',
    'வௌ': 'ntt',
    'வ்': 't;',
    'ஷா': '\\h',
    'ஷி': '\\p',
    'ஷீ': '\\P',
    'ஷு': '\\{',
    'ஷூ': '\\_',
    'ஷெ': 'n\\',
    'ஷே': 'N\\',
    'ஷை': 'i\\',
    'ஷொ': 'nh',
    'ஷோ': 'Nh',
    'ஷௌ': 'ns',
    'ஷ்': '\\;',
    'ஸா': ']h',
    'ஸி': ']p',
    'ஸீ': ']P',
    'ஸு': ']{',
    'ஸூ': ']_',
    'ஸெ': 'n]',
    'ஸே': 'N]',
    'ஸை': 'i]',
    'ஸொ': 'n]h',
    'ஸோ': 'N]h',
    'ஸௌ': 'n]s',
    'ஸ்': '];',
    'ஹா': '`h',
    'ஹி': '`p',
    'ஹீ': '`P',
    'ஹு': '`{',
    'ஹூ': '`_',
    'ஹெ': 'n`',
    'ஹே': 'N`',
    'ஹை': 'i`',
    'ஹொ': 'n`h',
    'ஹோ': 'N`h',
    'ஹௌ': 'n``',
    'ஹ்': '`;',
    'ஃ': '/',
    'அ': 'm',
    'ஆ': 'M',
    'இ': ',',
    'ஈ': '<',
    'உ': 'c',
    'ஊ': 'C',
    'எ': 'v',
    'ஏ': 'V',
    'ஐ': 'I',
    'ஒ': 'x',
    'ஓ': 'X',
    'ஔ': 'xs',
    'க': 'f',
    'ங': 'q',
    'ச': 'r',
    'ஜ': '[',
    'ஞ': 'Q',
    'ட': 'l',
    'ண': 'z',
    'த': 'j',
    'ந': 'e',
    'ன': 'd',
    'ப': 'g',
    'ம': 'k',
    'ய': 'a',
    'ர': 'u',
    'ற': 'w',
    'ல': 'y',
    'ள': 's',
    'ழ': 'o',
    'வ': 't',
    'ஷ': '\\',
    'ஸ': ']',
    'ஹ': '`',
}

_MAX_CLUSTER = max(len(k) for k in _UNICODE_TO_BAMINI)


def unicode_to_bamini(text: str) -> str:
    """Transliterate Unicode Tamil into Bamini's ASCII encoding.

    Characters with no Bamini equivalent are passed through unchanged.
    """
    out = []
    i = 0
    length = len(text)
    while i < length:
        for size in range(min(_MAX_CLUSTER, length - i), 0, -1):
            chunk = text[i : i + size]
            replacement = _UNICODE_TO_BAMINI.get(chunk)
            if replacement is not None:
                out.append(replacement)
                i += size
                break
        else:
            out.append(text[i])
            i += 1
    return "".join(out)
